recipes-packages: Fix squashfs size calculation by adding offset
Updated get_squashfs_size to add 65536 to the raw size extracted via dd,
ensuring accurate squashfs size computation.

Change-Id: Ie40d2acc5deb43713d596d79f32d3c3274edeaac
Signed-off-by: Sathishkumar Kumar <satku@qti.qualcomm.com>

diff --git a/sysupgrade/files/sysupgrade b/sysupgrade/files/sysupgrade
--- a/sysupgrade/files/sysupgrade
+++ b/sysupgrade/files/sysupgrade
@@ -316,6 +316,10 @@ esac
 
 if [ -n "$IMAGE" ] && type 'platform_check_image' >/dev/null 2>/dev/null; then
         platform_check_image "$IMAGE"
+	if [[ "$?" != 0 ]];then
+                echo "Image check failed." >&2
+                exit 1
+        fi
 fi
 
 if [ -n "$CONF_IMAGE" ]; then
